### PR TITLE
Add new claims to mitid-erhverv

### PR DESCRIPTION
**Pull request by nmoskaleva**

### CODE REVIEW

**Comment by sgryt** [comment]
@mickhansen Refresh my memory - where do we maintain the tooltips for claim types ?

**Comment by nmoskaleva** [comment]
@sgryt here is the PR: https://github.com/criipto/criipto-jwt-viewer/pull/11

**Comment by mickhansen** [comment]
`@criipto/jwt-viewer@1.2.0`

**Comment by mickhansen** [comment]
@nmoskaleva Please update the package version so the tooltips can take effect

**Comment by nmoskaleva** [comment]
@mickhansen missed that, sorry. Done now.

**Comment by mickhansen** [comment]
Thanks @nmoskaleva

**Pull request merged**
