### PR TITLE
Added description of how the consent features work for NO and DK.

### PR DESCRIPTION
**Pull request by sgryt**
[Pending QA of the runtime and management API changes]

### CODE REVIEW

**Comment by mickhansen** [comment]
@sgryt There is a build error of some sort, can you test `npm run build` locally?

**Comment by sgryt** [comment]
> @sgryt There is a build error of some sort, can you test `npm run build` locally?

I can see the changes in the browser, but perhaps I didn't use the correct incantations when creating a new .tsx component ?

**Comment by sgryt** [comment]
> > @sgryt There is a build error of some sort, can you test `npm run build` locally?
> 
> I can see the changes in the browser, but perhaps I didn't use the correct incantations when creating a new .tsx component ?

will try the `npm run build` locally and report back.

**Review by mickhansen — APPROVED** [review]

**Comment by mickhansen** [comment]
@sgryt Looks like the named vs default import was the issue, didn't even see the brackets when I reviewed the code haha

**Pull request merged**
