### PR TITLE
Try out @criipto/jwt-viewer

### PR DESCRIPTION
**Pull request by mickhansen**

### CODE REVIEW

**Comment by sgryt** [comment]
> @sgryt Keep-Alive, now with Netlify preview.
> 
> Take a look, if it seems like an improvement, i'll replace all the JWT examples.

@mickhansen Checks and preview deploy all failed ?

**Comment by mickhansen** [comment]
> > @sgryt Keep-Alive, now with Netlify preview.
> > Take a look, if it seems like an improvement, i'll replace all the JWT examples.
> 
> @mickhansen Checks and preview deploy all failed ?

@sgryt Aye, fixing now. jwt-viewer project had a `window` reference which doesn't work in SSG.

**Comment by sgryt** [comment]
> https://deploy-preview-37--criipto-docs.netlify.app/verify/e-ids/danish-mitid/

Readability is a bit worse for me than the old layout (contrast is easier on my eyes there, perhaps because the colours are less 'shiny'), but I seem to have the same problem with jwt.io now that I am actually putting some thought into it.
But the improved recognizability is still more important, so I vote to try the new version.

**Comment by mickhansen** [comment]
> > https://deploy-preview-37--criipto-docs.netlify.app/verify/e-ids/danish-mitid/
> 
> Readability is a bit worse for me than the old layout (contrast is easier on my eyes there, perhaps because the colours are less 'shiny'), but I seem to have the same problem with jwt.io now that I am actually putting some thought into it. But the improved recognizability is still more important, so I vote to try the new version.

Yeah I'm not liking the pink on white a whole lot either. Not sure why it bothers me less on JWT.io?

**Comment by mickhansen** [comment]
@sgryt jwt.io uses Roboto Mono instead of monospace, that could perhaps help?

**Comment by sgryt** [comment]
> @sgryt jwt.io uses Roboto Mono instead of monospace, that could perhaps help?

Perhaps - though it seems to be mostly an issue with blur on all the characters on the white/pink edges, not sure if the font will change that ?

**Comment by mickhansen** [comment]
> > @sgryt jwt.io uses Roboto Mono instead of monospace, that could perhaps help?
> 
> Perhaps - though it seems to be mostly an issue with blur on all the characters on the white/pink edges, not sure if the font will change that ?

It can in certain cases, depends a bit on anti aliasing and stuff. I've updated the font now, give it a shot.

**Comment by sgryt** [comment]
> > > @sgryt jwt.io uses Roboto Mono instead of monospace, that could perhaps help?
> > 
> > 
> > Perhaps - though it seems to be mostly an issue with blur on all the characters on the white/pink edges, not sure if the font will change that ?
> 
> It can in certain cases, depends a bit on anti aliasing and stuff. I've updated the font now, give it a shot (after netlify has updated).

That is actually better. Nice.

**Comment by sgryt** [comment]
> @sgryt Argh! merged before i could add it to all e-IDs :D Will commit on master.

@mickhansen Oh, damn, sorry !

**Pull request merged**
