### PR TITLE
aspnet-core-v6 tutorial

### PR DESCRIPTION
**Pull request by mickhansen**

### CODE REVIEW

**Comment by sgryt** [comment]
Not sure if related, but the search feature on the preview seems to be broken.
I get an entirely blank page when I enter a character in the search box (opened via `/`).

**Comment by sgryt** [comment]
image

**Comment by sgryt** [comment]
Old layout in the screenshot - perhaps update now ?

image

**Comment by sgryt** [comment]
```
The OIDC middleware requests both the openid and profile scopes by default, but note that Criipto Verify by nature returns only the information derived from the underlying e-ID service. Changing the scopes does not affect the amount and nature of information delivered from the user information endpoint.
```

is a bit outdated after the intro of dynamic scopes

**Comment by mickhansen** [comment]
> Old layout in the screenshot - perhaps update now ?
> 
> image

Wonder if we even need an image here?

**Comment by sgryt** [comment]
> > Old layout in the screenshot - perhaps update now ?
> > image
> 
> Wonder if we even need an image here?

Deep-link would be preferable, if possible.

**Comment by mickhansen** [comment]
@sgryt Updated with changes, including a deeplink instead of an image.

**Pull request merged**
